# **Step 1**
Lood dataset and necessary libraries, and inspect dataset for preprocessing

In [52]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

attr = pd.read_csv("Employee Data.csv")

In [53]:
attr

,Gender,Satisfaction,Business Travel,Department,EducationField,Salary,Home-Office,Attrition
0,Female,High,Rare,Sales,Engineering,Medium,Near,Yes
1,Male,Low,Frequent,Sales,Engineering,Low,Near,Yes
2,Male,Medium,Rare,R&D,Other,Medium,Far,No
3,Female,Low,Frequent,R&D,Engineering,Medium,Far,Yes
4,Male,Medium,Rare,R&D,Medical,Medium,Far,No
...,...,...,...,...,...,...,...,...
95,Female,High,Rare,R&D,Technical Degree,Medium,Near,No
96,Female,High,Rare,Sales,Other,Low,Near,Yes
97,Male,High,No,Sales,Medical,Medium,Near,No
98,Male,Medium,Rare,Sales,Medical,High,Near,No
99,Male,Low,No,R&D,Other,Low,Far,Yes

In [54]:
attr.info()
print("Dataset contains 100 observations. No missing values and all object data types that will need to be encoded")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Gender           100 non-null    object
 1   Satisfaction     100 non-null    object
 2   Business Travel  100 non-null    object
 3   Department       100 non-null    object
 4   EducationField   100 non-null    object
 5   Salary           100 non-null    object
 6   Home-Office      100 non-null    object
 7   Attrition        100 non-null    object
dtypes: object(8)
memory usage: 6.4+ KB
Dataset contains 100 observations. No missing values and all object data types that will need to be encoded

In [55]:
attr.duplicated().sum()

np.int64(9)

# **Step 2**
Next step is to carry out the data cleaning required based on the problems detected in the inspection of the previous step

In [56]:
from sklearn.preprocessing import LabelEncoder

In [57]:
attr = attr.drop_duplicates()

In [61]:
en = LabelEncoder()
feats = ['Home-Office', 'Gender', 'Department', 'EducationField', 'Attrition']

for feat in feats:
    attr[feat] = en.fit_transform(attr[feat])

In [59]:
encodings = {
    'Satisfaction': {
        'Low': 0,
        'Medium': 1,
        'High': 2
    },
    'Business Travel': {
         'No': 0,
         'Rare': 1,
         'Frequent': 2
    },
    'Salary': {
        'Low': 0,
        'Medium': 1,
        'High': 2
    }
}

attr = attr.replace(encodings)

C:\Users\HP\AppData\Local\Temp\ipykernel_23792\3678451992.py:19: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  attr = attr.replace(encodings)

In [62]:
attr.head(11)

,Gender,Satisfaction,Business Travel,Department,EducationField,Salary,Home-Office,Attrition
0,0,2,1,1,0,1,1,1
1,1,0,2,1,0,0,1,1
2,1,1,1,0,3,1,0,0
3,0,0,2,0,0,1,0,1
4,1,1,1,0,2,1,0,0
5,1,2,2,0,0,0,0,0
6,0,2,1,0,2,2,0,0
7,1,2,1,0,0,2,1,0
8,1,2,2,0,0,2,1,0
9,1,1,1,0,2,2,1,0
10,1,0,1,0,2,1,1,0

# **Step 3**
Next step is to carry out EDA and visualise key relationships